apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quiz-app
  template:
    metadata:
      labels:
        app: java-quiz-app
    spec:
      containers:
      - name: java-quiz-app
        image: tanishaaa31/java-quiz-app:latest
        ports:
        - containerPort: 8080
